version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master communication port for Spark workers
      - "4040:4040"  # for spark context viewing DAG
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark-master-volume:/bitnami/spark
      - ./data:/data
      - ./notebooks:/notebooks

  spark-worker-1:
    image: bitnami/spark:3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - spark-worker-1-volume:/bitnami/spark
      - ./data:/data  # Ensure workers have access to the same data directory


  spark-worker-2:
    image: bitnami/spark:3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - spark-worker-2-volume:/bitnami/spark
      - ./data:/data  # Ensure workers have access to the same data directory

  # pyspark-notebook:
  #   image: jupyter/pyspark-notebook
  #   ports:
  #     - "8888:8888"  # Jupyter Notebook
  #   depends_on:
  #     - spark-master
  #   environment:
  #     - SPARK_MASTER=spark://spark-master:7077
  #     - PYSPARK_DRIVER_PYTHON=jupyter
  #     - PYSPARK_DRIVER_PYTHON_OPTS=notebook
  #   volumes:
  #     - ./data:/home/jovyan/data

volumes:
  spark-master-volume:
  spark-worker-1-volume:
  spark-worker-2-volume:
